name: Run pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Run orchestrate
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
          RAWG_PAGES_PER_RUN: "5"
          PRICE_UPDATE_BATCH: "50"
          PRICE_STALE_DAYS: "7"
        run: python orchestrate.py
